import type { Config } from 'tailwindcss'

export default <Config>{
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        'inverse-on-surface': '#f2f1eb',
        'outline': '#747878',
        'on-primary-container': '#858383',
        'on-surface-variant': '#444748',
        'primary-container': '#1c1b1b',
        'tertiary-container': '#261900',
        'tertiary-fixed': '#ffdea5',
        'inverse-surface': '#30312d',
        'surface-container-high': '#eae8e2',
        'error': '#ba1a1a',
        'secondary-fixed-dim': '#c8c6c2',
        'on-tertiary-fixed-variant': '#5d4201',
        'primary-fixed-dim': '#c8c6c5',
        'on-primary-fixed-variant': '#474746',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#1c1b1b',
        'on-error': '#ffffff',
        'surface': '#fbf9f3',
        'on-secondary-container': '#636260',
        'primary-fixed': '#e5e2e1',
        'on-tertiary-container': '#a17f3b',
        'on-background': '#1b1c19',
        'inverse-primary': '#c8c6c5',
        'secondary': '#5f5e5b',
        'background': '#fbf9f3',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed': '#1c1c1a',
        'on-surface': '#1b1c19',
        'surface-container-highest': '#e4e2dd',
        'on-primary': '#ffffff',
        'tertiary-fixed-dim': '#e9c176',
        'on-secondary-fixed-variant': '#474744',
        'on-tertiary-fixed': '#261900',
        'on-tertiary': '#ffffff',
        'surface-dim': '#dcdad4',
        'surface-container-low': '#f5f3ee',
        'secondary-fixed': '#e5e2de',
        'tertiary': '#000000',
        'secondary-container': '#e2dfdb',
        'on-secondary': '#ffffff',
        'surface-variant': '#e4e2dd',
        'primary': '#000000',
        'surface-container': '#f0eee8',
        'surface-bright': '#fbf9f3',
        'outline-variant': '#c4c7c7',
        'surface-tint': '#5f5e5e',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-sm': '16px',
        'margin-md': '32px',
        'margin-lg': '64px',
        'section-padding': '120px',
        'container-max': '1140px',
        'gutter': '32px',
        'unit': '8px',
      },
      fontFamily: {
        'label-caps': ['Inter'],
        'body-md': ['Inter'],
        'headline-sm': ['Playfair Display'],
        'headline-md': ['Playfair Display'],
        'display-lg-mobile': ['Playfair Display'],
        'display-lg': ['Playfair Display'],
        'body-lg': ['Inter'],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'display-lg-mobile': ['40px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.8', letterSpacing: '0.01em', fontWeight: '400' }],
      },
    },
  },
}
